### ISSUE TITLE
收藏建议&资源提供

### ISSUE THREAD

**Issue by ske1996** [Kensuke-Hinata/statistic#8]
项目主您好，

非常感谢您的收藏，对我有极大的帮助（万恶的资本主义社会，书真尼玛贵）

我是学习数据科学和数理统计的，《利用 Python 进行数据分析 · 第 2 版》这本书非常的棒，我似乎没有在您这个项目里找到（或者是我眼拙了），如果可以收录进贵书单，感觉可以帮助更多的人

链接：https://pan.baidu.com/s/1EDjvInW_t18lHmrXC_Nyog 
提取码：0000

**Comment by junchuanwang** [comment]
@ske1996 大兄弟的链接已经不能用了 ”该链接已超过访问人数上限，可联系分享者重新分享“

**Comment by ske1996** [comment]
> 

链接: https://pan.baidu.com/s/1bbeG8A0aKauPQCjtvkjDag 提取码: mgs2

老哥你看看这个呢
